sudo: required
language: python

services:
  - docker

install:
  - pip install ome-ansible-molecule-dependencies

script:
  - cd $BASEDIR && molecule test

env:
  - BASEDIR: .
  - BASEDIR: allinone
  - BASEDIR: two-nodes
